-- ============================================================
-- tuckzed mods — Supabase Database & Storage Setup
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new
-- Safe to run more than once: existing tables/policies are skipped.
-- ============================================================

-- 1. Create the `mods` table
CREATE TABLE IF NOT EXISTS public.mods (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  version TEXT DEFAULT '1.0.0',
  game TEXT NOT NULL,         -- 'ac' or 'beamng'
  category TEXT NOT NULL,     -- 'Cars', 'Tracks', 'Maps', 'Physics'
  tags TEXT DEFAULT '',
  download_url TEXT DEFAULT '',
  downloads INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  cover_image TEXT DEFAULT '',
  images JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT DEFAULT 'admin'
);

-- If the table already exists, ensure newer columns are added:
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS tags TEXT DEFAULT '';
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS downloads INTEGER DEFAULT 0;
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.mods ENABLE ROW LEVEL SECURITY;

-- Policies are created only if they do not already exist (safe to re-run)
DO $$ BEGIN
  CREATE POLICY "Public Read Mods" ON public.mods FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Allow Manage Mods" ON public.mods FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 3. Create a public storage bucket for mod cover images
INSERT INTO storage.buckets (id, name, public)
VALUES ('mod-covers', 'mod-covers', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$ BEGIN
  CREATE POLICY "Public Read Cover Images" ON storage.objects FOR SELECT USING (bucket_id = 'mod-covers');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Allow Upload Cover Images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'mod-covers');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Allow Update Cover Images" ON storage.objects FOR UPDATE USING (bucket_id = 'mod-covers');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Allow Delete Cover Images" ON storage.objects FOR DELETE USING (bucket_id = 'mod-covers');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 4. Community tables used by comments, likes, profiles, and reports
CREATE TABLE IF NOT EXISTS public.profiles (
  email TEXT PRIMARY KEY,
  display_name TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mod_likes (
  mod_id TEXT NOT NULL,
  user_email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (mod_id, user_email)
);

CREATE TABLE IF NOT EXISTS public.mod_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mod_id TEXT NOT NULL,
  user_email TEXT DEFAULT 'anonymous',
  username TEXT DEFAULT '',
  comment TEXT NOT NULL,
  parent_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

-- Lets the site show an "edited" marker on comments (optional; the site works without it)
ALTER TABLE public.mod_comments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_id TEXT NOT NULL,
  target_type TEXT NOT NULL,
  reported_by TEXT DEFAULT 'anonymous',
  reason TEXT DEFAULT '',
  status TEXT DEFAULT 'pending',
  context_id TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Older installs may already have `reports` without these columns
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS reported_by TEXT DEFAULT 'anonymous';
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS reason TEXT DEFAULT '';
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS context_id TEXT DEFAULT '';
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
UPDATE public.reports SET status = 'pending' WHERE status IS NULL;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mod_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mod_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Public Read Profiles" ON public.profiles FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Public Read Likes" ON public.mod_likes FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Likes" ON public.mod_likes FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Public Read Comments" ON public.mod_comments FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Comments" ON public.mod_comments FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Reports" ON public.reports FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$ BEGIN
  CREATE POLICY "Public Read Avatars" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Upload Avatars" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Update Avatars" ON storage.objects FOR UPDATE USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Delete Avatars" ON storage.objects FOR DELETE USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 5. Indexes for common query patterns
CREATE INDEX IF NOT EXISTS mod_comments_mod_id_idx ON public.mod_comments (mod_id);
CREATE INDEX IF NOT EXISTS mod_comments_parent_id_idx ON public.mod_comments (parent_id);
CREATE INDEX IF NOT EXISTS mod_likes_mod_id_idx ON public.mod_likes (mod_id);
CREATE INDEX IF NOT EXISTS mod_likes_user_email_idx ON public.mod_likes (user_email);
CREATE INDEX IF NOT EXISTS mods_created_at_idx ON public.mods (created_at DESC);
CREATE INDEX IF NOT EXISTS mods_game_idx ON public.mods (game);
CREATE INDEX IF NOT EXISTS reports_status_idx ON public.reports (status);
CREATE INDEX IF NOT EXISTS reports_target_idx ON public.reports (target_type, target_id);

-- 6. Foreign keys with cascade cleanup (safe if already present)
DO $$ BEGIN
  ALTER TABLE public.mod_likes
    ADD CONSTRAINT mod_likes_mod_id_fkey
    FOREIGN KEY (mod_id) REFERENCES public.mods(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.mod_comments
    ADD CONSTRAINT mod_comments_mod_id_fkey
    FOREIGN KEY (mod_id) REFERENCES public.mods(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.mod_comments
    ADD CONSTRAINT mod_comments_parent_id_fkey
    FOREIGN KEY (parent_id) REFERENCES public.mod_comments(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 7. Atomic download counter
CREATE OR REPLACE FUNCTION public.increment_mod_downloads(p_id TEXT)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  next_count INTEGER;
BEGIN
  UPDATE public.mods
  SET downloads = COALESCE(downloads, 0) + 1,
      updated_at = NOW()
  WHERE id = p_id
  RETURNING downloads INTO next_count;
  RETURN COALESCE(next_count, 0);
END;
$$;

-- 8. Keep mods.likes in sync with mod_likes rows
CREATE OR REPLACE FUNCTION public.sync_mod_likes_count()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  target_mod TEXT;
  next_count INTEGER;
BEGIN
  target_mod := COALESCE(NEW.mod_id, OLD.mod_id);
  SELECT COUNT(*)::INTEGER INTO next_count FROM public.mod_likes WHERE mod_id = target_mod;
  UPDATE public.mods SET likes = next_count, updated_at = NOW() WHERE id = target_mod;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_mod_likes_count ON public.mod_likes;
CREATE TRIGGER trg_sync_mod_likes_count
AFTER INSERT OR DELETE ON public.mod_likes
FOR EACH ROW EXECUTE PROCEDURE public.sync_mod_likes_count();

-- 9. Touch mods.updated_at on row updates
CREATE OR REPLACE FUNCTION public.touch_mods_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_mods_updated_at ON public.mods;
CREATE TRIGGER trg_touch_mods_updated_at
BEFORE UPDATE ON public.mods
FOR EACH ROW EXECUTE PROCEDURE public.touch_mods_updated_at();

-- ============================================================
-- 10. Extended features (safe to re-run)
-- Compatibility, changelog, soft-delete, wishlists, reactions,
-- notifications, collections, community submissions
-- ============================================================

ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS compatibility TEXT DEFAULT '';
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS changelog JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS mods_deleted_at_idx ON public.mods (deleted_at);
CREATE INDEX IF NOT EXISTS mods_featured_idx ON public.mods (featured) WHERE featured = TRUE;

-- Wishlists (separate from likes)
CREATE TABLE IF NOT EXISTS public.mod_wishlists (
  mod_id TEXT NOT NULL,
  user_email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (mod_id, user_email)
);

DO $$ BEGIN
  ALTER TABLE public.mod_wishlists
    ADD CONSTRAINT mod_wishlists_mod_id_fkey
    FOREIGN KEY (mod_id) REFERENCES public.mods(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS mod_wishlists_user_email_idx ON public.mod_wishlists (user_email);
ALTER TABLE public.mod_wishlists ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Public Read Wishlists" ON public.mod_wishlists FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Wishlists" ON public.mod_wishlists FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Comment 👍 reactions
CREATE TABLE IF NOT EXISTS public.comment_reactions (
  comment_id BIGINT NOT NULL,
  user_email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (comment_id, user_email)
);

DO $$ BEGIN
  ALTER TABLE public.comment_reactions
    ADD CONSTRAINT comment_reactions_comment_id_fkey
    FOREIGN KEY (comment_id) REFERENCES public.mod_comments(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS comment_reactions_comment_id_idx ON public.comment_reactions (comment_id);
ALTER TABLE public.comment_reactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Public Read Comment Reactions" ON public.comment_reactions FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Comment Reactions" ON public.comment_reactions FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- In-app notifications (e.g. comment replies)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'reply',
  message TEXT NOT NULL DEFAULT '',
  link TEXT DEFAULT '',
  context_id TEXT DEFAULT '',
  from_user TEXT DEFAULT '',
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS notifications_user_email_idx ON public.notifications (user_email, read, created_at DESC);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Public Read Notifications" ON public.notifications FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Curated collections
CREATE TABLE IF NOT EXISTS public.collections (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  cover_image TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT DEFAULT 'admin'
);

CREATE TABLE IF NOT EXISTS public.collection_mods (
  collection_id TEXT NOT NULL,
  mod_id TEXT NOT NULL,
  position INTEGER DEFAULT 0,
  PRIMARY KEY (collection_id, mod_id)
);

DO $$ BEGIN
  ALTER TABLE public.collection_mods
    ADD CONSTRAINT collection_mods_collection_id_fkey
    FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.collection_mods
    ADD CONSTRAINT collection_mods_mod_id_fkey
    FOREIGN KEY (mod_id) REFERENCES public.mods(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_mods ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Public Read Collections" ON public.collections FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Collections" ON public.collections FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Public Read Collection Mods" ON public.collection_mods FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Collection Mods" ON public.collection_mods FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Community mod submissions (admin review queue)
CREATE TABLE IF NOT EXISTS public.mod_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  version TEXT DEFAULT '1.0.0',
  game TEXT NOT NULL,
  category TEXT NOT NULL,
  tags TEXT DEFAULT '',
  download_url TEXT DEFAULT '',
  compatibility TEXT DEFAULT '',
  cover_image TEXT DEFAULT '',
  status TEXT DEFAULT 'pending',
  submitted_by TEXT DEFAULT 'anonymous',
  submitter_name TEXT DEFAULT '',
  admin_notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS mod_submissions_status_idx ON public.mod_submissions (status, created_at DESC);
ALTER TABLE public.mod_submissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Public Read Submissions" ON public.mod_submissions FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Submissions" ON public.mod_submissions FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
