-- ============================================================
-- tuckzed mods — Supabase Database & Storage Setup
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new
-- ============================================================

-- 1. Create the `mods` table
CREATE TABLE IF NOT EXISTS public.mods (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  version TEXT DEFAULT '1.0.0',
  game TEXT NOT NULL,         -- 'ac' or 'beamng'
  category TEXT NOT NULL,     -- 'Cars', 'Tracks', 'Maps', 'Physics'
  tags TEXT DEFAULT '',
  download_url TEXT DEFAULT '',
  downloads INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  cover_image TEXT DEFAULT '',
  images JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT DEFAULT 'admin'
);

-- If the table already exists, ensure newer columns are added:
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS tags TEXT DEFAULT '';
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS downloads INTEGER DEFAULT 0;
ALTER TABLE public.mods ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.mods ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read mods on the website
CREATE POLICY "Public Read Mods" 
  ON public.mods 
  FOR SELECT 
  USING (true);

-- Allow inserting, updating, and deleting mods
CREATE POLICY "Allow Manage Mods" 
  ON public.mods 
  FOR ALL 
  USING (true) 
  WITH CHECK (true);

-- 3. Create a public storage bucket for mod cover images
INSERT INTO storage.buckets (id, name, public)
VALUES ('mod-covers', 'mod-covers', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage policies: anyone can view cover images
CREATE POLICY "Public Read Cover Images" 
  ON storage.objects 
  FOR SELECT 
  USING (bucket_id = 'mod-covers');

-- Allow uploading, updating, and deleting cover images
CREATE POLICY "Allow Upload Cover Images" 
  ON storage.objects 
  FOR INSERT 
  WITH CHECK (bucket_id = 'mod-covers');

CREATE POLICY "Allow Update Cover Images" 
  ON storage.objects 
  FOR UPDATE 
  USING (bucket_id = 'mod-covers');

CREATE POLICY "Allow Delete Cover Images" 
  ON storage.objects 
  FOR DELETE 
  USING (bucket_id = 'mod-covers');

-- 4. Community tables used by comments, likes, profiles, and reports
CREATE TABLE IF NOT EXISTS public.profiles (
  email TEXT PRIMARY KEY,
  display_name TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mod_likes (
  mod_id TEXT NOT NULL,
  user_email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (mod_id, user_email)
);

CREATE TABLE IF NOT EXISTS public.mod_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mod_id TEXT NOT NULL,
  user_email TEXT DEFAULT 'anonymous',
  username TEXT DEFAULT '',
  comment TEXT NOT NULL,
  parent_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_id TEXT NOT NULL,
  target_type TEXT NOT NULL,
  reported_by TEXT DEFAULT 'anonymous',
  reason TEXT DEFAULT '',
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mod_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mod_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Public Read Profiles" ON public.profiles FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Public Read Likes" ON public.mod_likes FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Likes" ON public.mod_likes FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Public Read Comments" ON public.mod_comments FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Comments" ON public.mod_comments FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Manage Reports" ON public.reports FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$ BEGIN
  CREATE POLICY "Public Read Avatars" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Upload Avatars" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Update Avatars" ON storage.objects FOR UPDATE USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Allow Delete Avatars" ON storage.objects FOR DELETE USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
